import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: import.meta.env.VITE_BASE_URL });

